#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Scorecard Markdown Writer (PHASE8)
===================================
Scorecard를 Markdown 형식으로 저장
"""
from pathlib import Path
from typing import Dict, Any


def save_scorecard_md(scorecard: Dict[str, Any], output_dir: Path) -> Path:
    """
    Scorecard를 Markdown으로 저장
    
    Args:
        scorecard: scorecard 데이터
        output_dir: 출력 디렉토리
    
    Returns:
        Path: 저장된 Markdown 파일 경로
    
    Examples:
        >>> scorecard = {
        ...     'strategy': 'scalping',
        ...     'winrate': 45.5,
        ...     'profit_factor': 1.25,
        ... }
        >>> output_dir = Path('artifacts/backtest_clean/20251114_135030_a7f3/')
        >>> path = save_scorecard_md(scorecard, output_dir)
    """
    # 디렉토리 생성
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Markdown 파일 경로
    md_path = output_dir / "scorecard.md"
    
    # 합격/불합격 판정
    passed = _check_criteria(scorecard)
    status_emoji = "✅ 합격" if passed else "❌ 불합격"
    
    # Markdown 작성
    content = f"""# 📊 Backtest Scorecard

## Strategy: {scorecard['strategy']}

- **Symbol**: {scorecard['symbol']}
- **Timeframe**: {scorecard['timeframe']}
- **Status**: {status_emoji}

---

## 📈 Performance Metrics

| Metric | Value | Target | Status |
|--------|-------|--------|--------|
| **Trades Closed** | {scorecard['trades_closed']} | ≥ 100 | {'✅' if scorecard['trades_closed'] >= 100 else '❌'} |
| **Winrate** | {scorecard['winrate']}% | ≥ 40% | {'✅' if scorecard['winrate'] >= 40 else '❌'} |
| **Profit Factor** | {scorecard['profit_factor']} | ≥ 1.10 | {'✅' if scorecard['profit_factor'] >= 1.10 else '❌'} |
| **Max Drawdown** | {scorecard['max_drawdown']}% | > -20% | {'✅' if scorecard['max_drawdown'] > -20 else '❌'} |
| **Loss > 8%** | {scorecard['loss_over_8pct']} | = 0 | {'✅' if scorecard['loss_over_8pct'] == 0 else '❌'} |
| **TP Hit Rate** | {scorecard['tp_hit']}% | - | - |
"""
    
    if 'sharpe_ratio' in scorecard:
        content += f"| **Sharpe Ratio** | {scorecard['sharpe_ratio']} | - | - |\n"
    
    content += f"""
---

## 🎯 Acceptance Criteria (PHASE8)

- **Winrate** ≥ 40%  
- **Profit Factor** ≥ 1.10  
- **Max Drawdown** > -20%  
- **Loss > 8%** = 0  
- **Trades Closed** ≥ 100  

**Overall Result**: {status_emoji}

---

*Generated by PHASE8 Scorecard System*
"""
    
    with open(md_path, 'w', encoding='utf-8') as f:
        f.write(content)
    
    return md_path


def _check_criteria(scorecard: Dict[str, Any]) -> bool:
    """
    PHASE8 합격 기준 체크
    
    Args:
        scorecard: scorecard 데이터
    
    Returns:
        bool: 합격 여부
    """
    return (
        scorecard['trades_closed'] >= 100 and
        scorecard['winrate'] >= 40.0 and
        scorecard['profit_factor'] >= 1.10 and
        scorecard['max_drawdown'] > -20.0 and
        scorecard['loss_over_8pct'] == 0
    )
